### ISSUE TITLE
getting some error while trying to use on windows

### ISSUE THREAD

**Issue by pankajniet** [codelucas/vsummarize#2]
Hi ,

Thanks for this module.

I was trying this module on my windows machine and was getting some Import error related to google setting ...
Please provide some necessary steps of installation and uses that will be a great help....

Here are the full logs for the same:

#>python
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 19 2016, 13:29:36) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import vsummarize
Fails when not using as a module No module named settings
This fails when not run as a module No module named settings
Fails when not using as a module No module named settings
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\pankaj\Anaconda3\envs\accv_vsum\lib\site-packages\vsummarize\__init__.py", line 13, in <module>
    from .api import summarize
  File "C:\Users\pankaj\Anaconda3\envs\accv_vsum\lib\site-packages\vsummarize\api.py", line 18, in <module>
    import youtube
  File "C:\Users\pankaj\Anaconda3\envs\accv_vsum\lib\site-packages\vsummarize\youtube.py", line 15, in <module>
    from settings import google_username, google_password
ImportError: No module named settings
>>>

Regards,
Pankaj

**Comment by pankajniet** [comment]
I think this bug is related to google data API as I saw one blog related to this "The YouTube Data API (v2) has been officially deprecated as of March 4, 2014." (https://stackoverflow.com/questions/33517357/youtube-api-v3-0-request-errors-python).

Any plan to upgrade this module with new YouTube data API (V3)?

**Comment by codelucas** [comment]
Thank you for filing this @pankajniet, this service has been broken for a while now due to the Youtube API v2->v3 migrations :(
